version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0

    steps:
      - checkout
      - run: yarn install
      - run: yarn build

  test:
    docker:
      - image: circleci/node:10.13.0

    steps:
      - checkout
      - run: yarn install
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test